export const jobs = [
  {
    id: 1,
    title: "Full Stack Developer",
    orgName: "Red Blocks IT",
    description:
      "Join our creative team to design and implement stunning user interfaces. This role involves collaboration with cross-functional teams to deliver seamless user experiences. If you excel in front-end technologies and love crafting engaging designs, apply now!",
    skills: ["JavaScript", "React", "CSS", "HTML"],
    jobRole: "Frontend Engineer",
    jobDesignation: "Software Engineer",
    degreeLevel: ["BSc."],
    fieldOfStudy: ["CSE", "EEE"],
    yearOfExperience: 1,
    location: "Banani, Dhaka, Bangladesh",
    requirements: [
      "Proficiency in JavaScript, React, and CSS.",
      "Strong understanding of responsive design.",
      "Experience with REST APIs.",
      "Version control (Git).",
      "Creative problem-solving skills.",
    ],
    responsibilities: [
      "Develop responsive web designs.",
      "Collaborate with designers to bring mockups to life.",
      "Ensure the technical feasibility of UI/UX designs.",
      "Optimize applications for performance.",
      "Stay updated with the latest front-end trends.",
    ],
    employeeBenefits: [
      "Attractive salary and yearly bonuses.",
      "Health and wellness coverage.",
      "Flexible work schedules.",
      "Learning opportunities and certifications.",
      "Annual retreats and team activities.",
    ],
    salary: 5000,
    phone: "+8801405-123456",
    email: "frontend-career@example.com",
    contactInfo: "Career Team",
    employeeType: "full-time",
    jobType: "onsite",
    steps: ["portfolio review", "technical test", "interview"],
    applicantCount: 50,
    deadline: "2024-12-15",
    published: "2024-11-20",
    isApplied: true,
    status: "Applied",
  },
  {
    id: 2,
    title: "Backend Developer",
    orgName: "Orion Digital Ltd.",
    description:
      "We're looking for a Backend Developer to build robust APIs and backend systems. You'll work closely with the front-end team to ensure seamless integration and efficient data handling. Join us if you're passionate about backend technologies and system architecture.",
    skills: ["Node.js", "Express", "MongoDB", "SQL"],
    jobRole: "Backend Engineer",
    jobDesignation: "Software Engineer",
    degreeLevel: ["MSc.", "BSc."],
    fieldOfStudy: ["CSE", "ETE"],
    yearOfExperience: 2,
    location: "Uttara, Dhaka, Bangladesh",
    requirements: [
      "Proficiency in Node.js and Express.",
      "Experience with database management.",
      "Knowledge of REST APIs.",
      "Problem-solving skills.",
      "Ability to work collaboratively.",
    ],
    responsibilities: [
      "Develop backend systems and APIs.",
      "Optimize application performance.",
      "Ensure data security and integrity.",
      "Collaborate with other developers and stakeholders.",
      "Stay updated on new backend technologies.",
    ],
    employeeBenefits: [
      "Competitive salary and incentives.",
      "Medical and life insurance.",
      "Remote work flexibility.",
      "Paid leave and holidays.",
      "Professional development and training.",
    ],
    salary: 7000,
    phone: "+8801405-789456",
    email: "backend-career@example.com",
    contactInfo: "Recruitment Team",
    employeeType: "full-time",
    jobType: "remote",
    steps: ["screening test", "technical interview", "final interview"],
    applicantCount: 40,
    deadline: "2024-12-30",
    published: "2024-11-28",
    isApplied: true,
    status: "Rejected",
  },
  {
    id: 3,
    title: "Full Stack Developer",
    orgName: "Maxsun Innovation",
    description:
      "Be a vital part of our development team by creating and maintaining full-stack applications. This role demands expertise in both front-end and back-end technologies to deliver complete solutions.",
    skills: ["JavaScript", "React", "Node.js", "Express"],
    jobRole: "Full Stack Engineer",
    jobDesignation: "Software Developer",
    degreeLevel: ["BSc.", "MSc."],
    fieldOfStudy: ["CSE", "EEE"],
    yearOfExperience: 2,
    location: "Mirpur, Dhaka, Bangladesh",
    requirements: [
      "Proficient in JavaScript and React.",
      "Experience with Node.js and Express.",
      "Strong problem-solving skills.",
      "Understanding of RESTful APIs.",
      "Database knowledge (SQL/NoSQL).",
    ],
    responsibilities: [
      "Build and maintain full-stack web applications.",
      "Collaborate with teams for seamless development.",
      "Write maintainable, efficient code.",
      "Debug and troubleshoot issues.",
      "Implement secure and scalable solutions.",
    ],
    employeeBenefits: [
      "Competitive salary and performance bonuses.",
      "Health and wellness plans.",
      "Remote working options.",
      "Paid leave and vacation days.",
      "Professional growth opportunities.",
    ],
    salary: 8000,
    phone: "+8801405-987654",
    email: "fullstack-career@example.com",
    contactInfo: "Tech Team",
    employeeType: "contractual",
    jobType: "remote",
    steps: ["resume review", "online coding test", "technical interview"],
    applicantCount: 60,
    deadline: "2024-12-20",
    published: "2025-01-04",
    isApplied: true,
    status: "Shortlisted",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    orgName: "Mediusware Ltd.",
    description:
      "As a DevOps Engineer, you will streamline our development and deployment processes. You'll implement CI/CD pipelines, monitor infrastructure, and ensure reliable delivery of software solutions.",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    jobRole: "DevOps Specialist",
    jobDesignation: "Infrastructure Engineer",
    degreeLevel: ["BSc."],
    fieldOfStudy: ["CSE", "EEE"],
    yearOfExperience: 3,
    location: "Mohakhali, Dhaka, Bangladesh",
    requirements: [
      "Hands-on experience with Docker and Kubernetes.",
      "Proficiency in cloud platforms (AWS preferred).",
      "Strong understanding of CI/CD pipelines.",
      "Knowledge of monitoring tools (e.g., Prometheus, Grafana).",
      "Problem-solving and automation skills.",
    ],
    responsibilities: [
      "Implement and maintain CI/CD pipelines.",
      "Monitor system performance and ensure uptime.",
      "Collaborate with developers for smooth deployments.",
      "Automate repetitive tasks to improve efficiency.",
      "Research and adopt new DevOps tools.",
    ],
    employeeBenefits: [
      "Competitive salary and allowances.",
      "Health insurance and wellness programs.",
      "Remote work options.",
      "Professional development and certifications.",
      "Team retreats and bonuses.",
    ],
    salary: 10000,
    phone: "+8801405-456789",
    email: "devops-career@example.com",
    contactInfo: "Operations Team",
    employeeType: "full-time",
    jobType: "onsite",
    steps: ["technical test", "case study", "final interview"],
    applicantCount: 30,
    deadline: "2024-12-25",
    published: "2024-12-10",
    isApplied: false,
    status: "",
  },
  {
    id: 5,
    title: "QA Engineer",
    orgName: "Acnoo Limited",
    description:
      "Join our team as a QA Engineer to ensure the delivery of high-quality software products. You'll create and execute test plans, identify bugs, and collaborate with developers to resolve issues.",
    skills: ["Manual Testing", "Automation Testing", "Selenium", "Postman"],
    jobRole: "Quality Assurance Engineer",
    jobDesignation: "QA Specialist",
    degreeLevel: ["BSc."],
    fieldOfStudy: ["CSE", "EEE"],
    yearOfExperience: 1,
    location: "Dhanmondi, Dhaka, Bangladesh",
    requirements: [
      "Experience in manual and automated testing.",
      "Proficiency with testing tools like Selenium and Postman.",
      "Strong analytical and problem-solving skills.",
      "Excellent communication and documentation abilities.",
      "Knowledge of Agile methodologies.",
    ],
    responsibilities: [
      "Develop and execute comprehensive test plans.",
      "Identify, document, and track bugs.",
      "Collaborate with developers to resolve issues.",
      "Perform regression and performance testing.",
      "Ensure compliance with quality standards.",
    ],
    employeeBenefits: [
      "Attractive salary package.",
      "Health insurance and wellness programs.",
      "Flexible working hours.",
      "Professional training and certifications.",
      "Team-building activities.",
    ],
    salary: 5500,
    phone: "+8801405-321654",
    email: "qa-career@example.com",
    contactInfo: "QA Team",
    employeeType: "contractual",
    jobType: "onsite",
    steps: ["aptitude test", "technical interview", "HR interview"],
    applicantCount: 25,
    deadline: "2024-12-18",
    published: "2025-01-01",
    isApplied: true,
    status: "Applied",
  },
  {
    id: 6,
    title: "Mobile App Developer",
    orgName: "Bluelight Digital Inovix",
    description:
      "Develop high-quality mobile applications for Android and iOS platforms. Work with cutting-edge tools to deliver seamless user experiences.",
    skills: ["React Native", "Flutter", "Java", "Kotlin"],
    jobRole: "Mobile Developer",
    jobDesignation: "Software Developer",
    degreeLevel: ["BSc."],
    fieldOfStudy: ["CSE", "ETE"],
    yearOfExperience: 2,
    location: "Gulshan, Dhaka, Bangladesh",
    requirements: [
      "Proficiency in React Native or Flutter.",
      "Experience with Android and iOS development.",
      "Strong problem-solving and debugging skills.",
      "Knowledge of mobile app architecture.",
      "Understanding of APIs and backend integration.",
    ],
    responsibilities: [
      "Design and build advanced mobile applications.",
      "Collaborate with cross-functional teams.",
      "Write clean, maintainable code.",
      "Debug and optimize application performance.",
      "Stay updated on mobile development trends.",
    ],
    employeeBenefits: [
      "Competitive salary.",
      "Comprehensive health coverage.",
      "Flexible working hours.",
      "Learning and development opportunities.",
      "Team-building events.",
    ],
    salary: 7500,
    phone: "+8801405-159753",
    email: "mobile-dev-career@example.com",
    contactInfo: "Mobile Team",
    employeeType: "full-time",
    jobType: "onsite",
    steps: ["portfolio review", "technical test", "final interview"],
    applicantCount: 35,
    deadline: "2024-12-22",
    published: "2024-12-16",
    isApplied: false,
    status: "Applied",
  },
  {
    id: 7,
    title: "UI/UX Designer",
    orgName: "Next Hub Limited",
    description:
      "Craft visually appealing and user-friendly designs. Work closely with developers to create cohesive and intuitive interfaces.",
    skills: ["Figma", "Adobe XD", "Photoshop", "Sketch"],
    jobRole: "UI/UX Specialist",
    jobDesignation: "Product Designer",
    degreeLevel: ["BSc.", "Diploma"],
    fieldOfStudy: ["CSE", "Graphic Design"],
    yearOfExperience: 1,
    location: "Baridhara, Dhaka, Bangladesh",
    requirements: [
      "Proficiency in Figma, Adobe XD, and Sketch.",
      "Strong understanding of design principles.",
      "Experience with wireframes and prototypes.",
      "Excellent communication and teamwork skills.",
      "Creativity and attention to detail.",
    ],
    responsibilities: [
      "Design user interfaces and experiences.",
      "Collaborate with developers and stakeholders.",
      "Create wireframes and prototypes.",
      "Test designs for usability.",
      "Stay updated with design trends.",
    ],
    employeeBenefits: [
      "Competitive salary with performance bonuses.",
      "Health insurance.",
      "Paid vacations and holidays.",
      "Access to design workshops.",
      "Collaborative work environment.",
    ],
    salary: 6000,
    phone: "+8801405-852456",
    email: "uiux-career@example.com",
    contactInfo: "Design Team",
    employeeType: "contractual",
    jobType: "remote",
    steps: ["portfolio review", "design test", "interview"],
    applicantCount: 20,
    deadline: "2024-12-15",
    published: "2024-10-23",
    isApplied: true,
    status: "Shortlisted",
  },
  {
    id: 8,
    title: "Product Manager",
    orgName: "Rokomari.com",
    description:
      "Lead product development cycles, work closely with cross-functional teams, and ensure successful product launches.",
    skills: ["Project Management", "Agile", "Scrum", "JIRA"],
    jobRole: "Product Manager",
    jobDesignation: "Project Lead",
    degreeLevel: ["MBA", "BSc."],
    fieldOfStudy: ["CSE", "BBA"],
    yearOfExperience: 3,
    location: "Dhanmondi, Dhaka, Bangladesh",
    requirements: [
      "Experience in project and product management.",
      "Proficiency with JIRA and Agile methodologies.",
      "Excellent communication skills.",
      "Strong organizational abilities.",
      "Proven leadership skills.",
    ],
    responsibilities: [
      "Plan and manage product development.",
      "Define product roadmap and strategy.",
      "Collaborate with stakeholders and teams.",
      "Monitor project progress and timelines.",
      "Ensure quality and timely delivery.",
    ],
    employeeBenefits: [
      "Attractive salary package.",
      "Health insurance.",
      "Performance bonuses.",
      "Training and certification programs.",
      "Collaborative work environment.",
    ],
    salary: 12000,
    phone: "+8801405-963852",
    email: "product-career@example.com",
    contactInfo: "Management Team",
    employeeType: "full-time",
    jobType: "onsite",
    steps: ["screening", "case study", "final interview"],
    applicantCount: 15,
    deadline: "2024-12-28",
    published: "2024-12-30",
    isApplied: true,
    status: "Rejected",
  },
  {
    id: 9,
    title: "DevOps Engineer",
    orgName: "Dynamo House Ltd",
    description:
      "Automate and optimize the development process using the latest DevOps tools and practices. Ensure seamless deployment and system reliability.",
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins"],
    jobRole: "DevOps Engineer",
    jobDesignation: "System Engineer",
    degreeLevel: ["BSc."],
    fieldOfStudy: ["CSE", "EEE"],
    yearOfExperience: 2,
    location: "Banani, Dhaka, Bangladesh",
    requirements: [
      "Experience with cloud platforms like AWS.",
      "Proficiency in Docker and Kubernetes.",
      "Knowledge of CI/CD pipelines.",
      "Strong scripting skills (Bash, Python).",
      "Understanding of system monitoring tools.",
    ],
    responsibilities: [
      "Design and maintain CI/CD pipelines.",
      "Ensure system scalability and reliability.",
      "Collaborate with development teams.",
      "Automate system processes and tasks.",
      "Monitor system performance and troubleshoot issues.",
    ],
    employeeBenefits: [
      "Competitive salary and bonuses.",
      "Comprehensive health insurance.",
      "Remote working opportunities.",
      "Access to the latest DevOps tools.",
      "Training and development programs.",
    ],
    salary: 10000,
    phone: "+8801405-321654",
    email: "devops-career@example.com",
    contactInfo: "DevOps Team",
    employeeType: "full-time",
    jobType: "onsite",
    steps: ["technical test", "scenario test", "final interview"],
    applicantCount: 25,
    deadline: "2024-12-30",
    published: "2024-10-24",
    isApplied: true,
    status: "Applied",
  },
  {
    id: 10,
    title: "Data Scientist",
    orgName: "Sanjin Tech Ltd",
    description:
      "Analyze complex datasets and generate actionable insights to solve business problems and drive data-driven decisions.",
    skills: ["Python", "Machine Learning", "SQL", "Data Visualization"],
    jobRole: "Data Analyst",
    jobDesignation: "Data Scientist",
    degreeLevel: ["MSc.", "BSc."],
    fieldOfStudy: ["CSE", "Mathematics", "Statistics"],
    yearOfExperience: 3,
    location: "Uttara, Dhaka, Bangladesh",
    requirements: [
      "Experience in data analysis and machine learning.",
      "Proficiency in Python and SQL.",
      "Knowledge of data visualization tools (Tableau, Power BI).",
      "Strong mathematical and statistical skills.",
      "Problem-solving and communication skills.",
    ],
    responsibilities: [
      "Develop predictive models and machine learning algorithms.",
      "Analyze datasets to identify trends and patterns.",
      "Collaborate with cross-functional teams for data-driven projects.",
      "Create and present visualizations for stakeholders.",
      "Stay updated on the latest data science tools and methods.",
    ],
    employeeBenefits: [
      "High salary with incentives.",
      "Health insurance and wellness programs.",
      "Flexible working hours.",
      "Access to advanced data tools.",
      "Professional development opportunities.",
    ],
    salary: 15000,
    phone: "+8801405-654789",
    email: "data-scientist@example.com",
    contactInfo: "Data Science Team",
    employeeType: "contractual",
    jobType: "remote",
    steps: ["data analysis test", "case study", "final interview"],
    applicantCount: 18,
    deadline: "2024-12-25",
    published: "2024-12-12",
  },
  {
    id: 11,
    title: "Quality Assurance Engineer",
    orgName: "Global Labs",
    description:
      "Ensure the delivery of high-quality software through rigorous testing and debugging processes, focusing on performance and reliability.",
    skills: ["Manual Testing", "Automation Tools", "Selenium", "Postman"],
    jobRole: "QA Engineer",
    jobDesignation: "Software Tester",
    degreeLevel: ["BSc.", "Diploma"],
    fieldOfStudy: ["CSE", "Software Engineering"],
    yearOfExperience: 1,
    location: "Motijheel, Dhaka, Bangladesh",
    requirements: [
      "Proficiency in manual and automated testing.",
      "Experience with testing tools like Selenium and Postman.",
      "Knowledge of bug tracking systems.",
      "Strong attention to detail.",
      "Good communication and documentation skills.",
    ],
    responsibilities: [
      "Develop and execute test plans.",
      "Identify and document bugs and issues.",
      "Collaborate with development teams to resolve issues.",
      "Perform regression and performance testing.",
      "Ensure compliance with quality standards.",
    ],
    employeeBenefits: [
      "Competitive salary and benefits.",
      "Health insurance coverage.",
      "Opportunities for career growth.",
      "Work-life balance initiatives.",
      "Regular team-building activities.",
    ],
    salary: 7000,
    phone: "+8801405-987654",
    email: "qa-career@example.com",
    contactInfo: "QA Team",
    employeeType: "full-time",
    jobType: "onsite",
    steps: ["bug finding test", "scenario test", "final interview"],
    applicantCount: 40,
    deadline: "2024-12-20",
    published: "2024-12-03",
    isApplied: false,
    status: "",
  },
  {
    id: 12,
    title: "Cybersecurity Specialist",
    orgName: "Nextgen Inovation",
    description:
      "Protect organizational systems and data by identifying vulnerabilities, implementing security measures, and responding to security incidents.",
    skills: [
      "Cybersecurity",
      "Penetration Testing",
      "Network Security",
      "Firewall Management",
    ],
    jobRole: "Security Analyst",
    jobDesignation: "Cybersecurity Specialist",
    degreeLevel: ["BSc."],
    fieldOfStudy: ["CSE", "Network Security"],
    yearOfExperience: 2,
    location: "Bashundhara, Dhaka, Bangladesh",
    requirements: [
      "Experience in cybersecurity and penetration testing.",
      "Knowledge of network and system security.",
      "Proficiency in security tools and firewalls.",
      "Ability to analyze and mitigate security threats.",
      "Strong problem-solving and technical skills.",
    ],
    responsibilities: [
      "Monitor and protect system security.",
      "Perform regular security assessments.",
      "Develop and implement security protocols.",
      "Respond to and resolve security breaches.",
      "Train staff on security best practices.",
    ],
    employeeBenefits: [
      "Attractive salary with bonuses.",
      "Comprehensive health insurance.",
      "Access to the latest security tools.",
      "Flexible work schedule.",
      "Training and certification programs.",
    ],
    salary: 12000,
    phone: "+8801405-112233",
    email: "cybersecurity@example.com",
    contactInfo: "Security Team",
    employeeType: "full-time",
    jobType: "onsite",
    steps: ["vulnerability test", "scenario analysis", "final interview"],
    applicantCount: 22,
    deadline: "2024-12-27",
    published: "2024-11-11",
    isApplied: false,
    status: "",
  },
];
