export const dummyUsers = [
    {
      E_id: 1,
      name: "Cy Ganderton",
      designation: "Quality Control Specialist",
      access: "editor",
      location: "Canada",
      favoriteColor: "Blue",
    },
    {
      E_id: 2,
      name: "Hart Hagerty",
      designation: "Desktop Support Technician",
      access: "viewer",
      location: "United States",
      favoriteColor: "Purple",
    },
    {
      E_id: 3,
      name: "Brice Swyre",
      designation: "Tax Accountant",
      access: "viewer",
      location: "China",
      favoriteColor: "Red",
    },
    {
      E_id: 4,
      name: "Marjy Ferencz",
      designation: "Office Assistant I",
      access: "editor",
      location: "Russia",
      favoriteColor: "Crimson",
    },
    {
      E_id: 5,
      name: "Yancy Tear",
      designation: "Community Outreach Specialist",
      access: "viewer",
      location: "Brazil",
      favoriteColor: "Indigo",
    },
    {
      E_id: 6,
      name: "Irma Vasilik",
      designation: "Editor",
      access: "editor",
      location: "Venezuela",
      favoriteColor: "Purple",
    },
  ];