export const jobData = [
    {
        id: "m5gr84i9",
        title: "Full-Stack Engineer",
        position: "Junior Backend Engineer",
        salary: 40000,
        status: "open",
        applications: 50,
        deadline: new Date("2024-12-31"),
        postedOn: new Date("2024-10-15"),
    },
    {
        id: "3u1reuv4",
        title: "Full-Stack Engineer",
        position: "Junior Backend Engineer",
        salary: 40000,
        applications: 67,
        status: "open",
        deadline: new Date("2024-12-31"),
        postedOn: new Date("2024-10-15"),
    },
    {
        id: "derv1ws0",
        title: "Full-Stack Engineer",
        position: "Junior Backend Engineer",
        salary: 40000,
        applications: 132,
        status: "open",
        deadline: new Date("2024-12-31"),
        postedOn: new Date("2024-10-15"),
    },
    {
        id: "5kma53ae",
        title: "Full-Stack Engineer",
        position: "Junior Backend Engineer",
        salary: 40000,
        applications: 23,
        status: "closed",
        deadline: new Date("2024-12-31"),
        postedOn: new Date("2024-10-15"),
    },
    {
        id: "bhqecj4p",
        title: "Full-Stack Engineer",
        position: "Junior Backend Engineer",
        salary: 40000,
        applications: 71,
        status: "closed",
        deadline: new Date("2024-12-31"),
        postedOn: new Date("2024-10-15"),
    },
];