// // Mock list of skills
// export const allSkills = [
//     "Project Management",
//     "Risk Management",
//     "Scheduling & Planning",
//     "Budgeting & Cost Control",
//     "Process Optimization",
//     "Resource Allocation",
//     "Data Analysis",
//     "Market Research",
//     "Data Entry & Management",
//     "Statistical Analysis",
//     "Inventory Management",
//     "Logistics & Distribution",
//     "Procurement",
//     "Warehouse Management",
//     "Vendor Management",
//     "Equipment Operation",
//     "Quality Control & Assurance",
//     "Assembly Line Management",
//     "Safety Procedures & Regulations",
//     "Lean Manufacturing Principles",
//     "CAD (Computer-Aided Design)",
//     "Blueprint Reading",
//     "Drafting & Prototyping",
//     "Electrical Wiring & Systems",
//     "Mechanical Fabrication",
//     "Patient Care & Nursing",
//     "Medical Coding & Billing",
//     "Diagnostic Equipment Operation",
//     "Surgical Assistance",
//     "Customer Service",
//     "Communication Skills",
//     "Negotiation Skills",
//     "Time Management",
//     "Leadership & Team Management",
//     "Problem Solving",
//     "Conflict Resolution",
//     "Decision Making",
//     "Adaptability",
//     "Collaboration & Teamwork",
//     "Presentation Skills",
//     "Sales Techniques",
//     "Marketing Strategy",
//     "Public Speaking",
//     "Creativity & Innovation",
//     "Financial Analysis",
//     "Taxation & Compliance",
//     "Legal Research",
//     "Contract Negotiation",
//     "Writing & Editing",
//     "Content Creation",
//     "Multitasking",
//     "Analytical Thinking",
//     "Decision-Making",
//     "Event Planning",
//     "Social Media Management",
//     "Networking",
//     "Customer Relationship Management",
//     "Product Management",
//     "Inventory Control",
//     "Technical Support",
//     "Conflict Management",
//     "Health and Safety Regulations",
//     "Educational Training & Development",
//     "Diversity & Inclusion Initiatives",
//     "Documentation & Reporting",
//     "HR Policies & Compliance",
//     "Performance Management",
//     "Employee Relations",
//     "Employee Recruitment & Hiring",
//     "Financial Reporting",
//     "Forecasting",
//     "Software & Hardware Troubleshooting",
//     "B2B Sales",
//     "E-commerce Management",
//     "Digital Marketing",
//     "SEO & SEM",
//     "Social Media Advertising",
//     "Web Analytics",
//     "Cloud Services Management",
//     "Business Intelligence",
//     "JavaScript",
//     "TypeScript",
//     "Python",
//     "Ruby",
//     "PHP",
//     "Java",
//     "C++",
//     "C#",
//     "Swift",
//     "Kotlin",
//     "HTML",
//     "CSS",
//     "SQL",
//     "NoSQL",
//     "MongoDB",
//     "MySQL",
//     "PostgreSQL",
//     "React",
//     "Angular",
//     "Vue.js",
//     "Express",
//     "Node.js",
//     "Next.js",
//     "Django",
//     "Flask",
//     "Ruby on Rails",
//     "Laravel",
//     "Symfony",
//     "Spring Boot",
//     ".NET",
//     "jQuery",
//     "Bootstrap",
//     "REST APIs",
//     "GraphQL",
//     "WebSockets",
//     "Single Page Application (SPA) Development",
//     "Firebase",
//     "Redis",
//     "Elasticsearch",
//     "Git",
//     "GitHub",
//     "GitLab",
//     "Bitbucket",
//     "GitFlow",
//     "GitOps",
//     "Jenkins",
//     "Travis CI",
//     "CircleCI",
//     "AWS (EC2, S3, Lambda, RDS)",
//     "Google Cloud Platform (GCP)",
//     "Microsoft Azure",
//     "Serverless Architecture",
//     "Docker",
//     "Kubernetes",
//     "Terraform",
//     "Ansible",
//     "Chef",
//     "Prometheus",
//     "Grafana",
//     "ELK Stack",
//     "React Native",
//     "Swift (iOS)",
//     "Kotlin (Android)",
//     "Flutter",
//     "Xamarin",
//     "TensorFlow",
//     "PyTorch",
//     "Keras",
//     "Natural Language Processing (NLP)",
//     "Computer Vision",
//     "Scikit-learn",
//     "OpenCV",
//     "Penetration Testing",
//     "Ethical Hacking",
//     "Firewall Configuration",
//     "Encryption & Decryption",
//     "VPN & Secure Network Configuration",
//     "Adobe Photoshop",
//     "Illustrator",
//     "Sketch",
//     "Figma",
//     "InVision",
//     "CorelDRAW",
//     "GIMP",
//     "Wireframing & Prototyping",
//     "User Research & Testing",
//     "Interaction Design",
//     "Design Systems",
//     "Usability & Accessibility Best Practices",
//     "Adobe Premiere Pro",
//     "Final Cut Pro",
//     "After Effects",
//     "DaVinci Resolve",
//     "Motion Graphics & Animation",
//     "3D Modeling",
//     "AutoCAD",
//     "Rhino",
//     "Unity",
//     "Unreal Engine",
//     "Cinema 4D",
//     "SolidWorks",
//     "CNC Machine Operation",
//     "Mechanical Fabrication",
//     "Robotics & Automation",
//     "Circuit Design & Analysis",
//     "PLC Programming",
//     "Power Distribution Systems",
//     "Renewable Energy Systems",
//     "Signal Processing",
//     "Structural Analysis",
//     "Construction Project Management",
//     "AutoCAD Civil 3D",
//     "Geotechnical Engineering",
//     "Surveying & Site Analysis",
//     "ISO 9001",
//     "Inspection Techniques",
//     "Six Sigma",
//     "Lean Manufacturing",
//     "Failure Analysis & Testing",
//     "Material Testing",
//     "Health IT Systems (EHR/EMR)",
//     "HIPAA Compliance",
//     "Medical Billing & Coding",
//     "Healthcare Policy & Procedures",
//     "Insurance & Claims Processing",
//     "Pharmaceutical Compounding",
//     "Prescription Verification",
//     "Drug Interaction Knowledge",
//     "Pharmacovigilance",
//     "Dispensing & Medication Management",
//     "BambooHR",
//     "Gusto",
//     "ADP",
//     "Talent Acquisition & Recruitment",
//     "Employee Onboarding",
//     "Payroll & Benefits Administration",
//     "HRIS Systems",
//     "Salesforce",
//     "HubSpot CRM",
//     "Google Ads",
//     "Facebook Ads",
//     "LinkedIn Ads",
//     "SEO",
//     "SEM",
//     "Content Marketing",
//     "Affiliate Marketing",
//     "Marketing Automation",
//     "Lead Generation & Nurturing",
//     "Zendesk",
//     "Freshdesk",
//     "Intercom",
//     "Drift",
//     "Helpdesk Systems & Ticketing",
//     "Conflict Resolution",
//     "Risk Management",
//     "E-commerce Platforms",
//     "Shopify",
//     "WooCommerce",
//     "Magento",
//     "BigCommerce",
//     "Squarespace",
//     "Payment Gateways",
//     "Order Fulfillment Systems",
//     "Product Information Management",
//     "Omnichannel Retailing",
//     "Customer Journey Mapping",
//     "Return & Exchange Policies",
//     "Customer Loyalty Programs",
//     "Blockchain Development",
//     "Ethereum",
//     "Hyperledger",
//     "Smart Contracts",
//     "Cryptography & Encryption",
//     "Tokenomics",
//     "ICOs",
//     "NFTs",
//     "Renewable Energy Systems",
//     "Carbon Footprint Calculation",
//     "Environmental Impact Assessments",
//     "Waste Management",
//     "Learning Management Systems (LMS)",
//     "Curriculum Development",
//     "Instructional Design",
//     "Online Education Platforms",
//     "Hotel Management Systems",
//     "Event Planning & Coordination",
//     "Tourism Marketing",
//     "Customer Service in Hospitality",
//     "Adobe Premiere Pro",
//     "Final Cut Pro",
//     "After Effects",
//     "DaVinci Resolve",
//     "Motion Graphics & Animation",
//     "3D Modeling (Blender, Autodesk Maya)",
//     "Event Planning & Coordination",
//     "Branding & Identity Design",
//     "Legal Research",
//     "Contract Drafting & Negotiation",
//     "Intellectual Property (Patents, Trademarks)",
//     "Litigation Support",
//     "Compliance & Regulatory Affairs",
//     "Due Diligence",
//     "GDPR Compliance",
//     "Anti-Money Laundering (AML)",
//     "Corporate Governance",
//     "Regulatory Reporting",
//     "Fraud Detection & Prevention",
//     "Digital Marketing",
//     "SEO & SEM",
//     "Social Media Advertising",
//     "Web Analytics",
//     "Cloud Services Management",
//     "Business Intelligence"

// ];

// export const degreeLevelData = [
//         "BSc",
//         "MSc",
//         "MBA",
//         "PhD",
//         "Associate Degree",
//         "Bachelor of Arts (BA)",
//         "Master of Arts (MA)",
//         "Doctor of Education (EdD)",
//         "Doctor of Philosophy (PhD)",
//         "Master of Business Administration (MBA)",
//         "Bachelor of Fine Arts (BFA)",
//         "Master of Fine Arts (MFA)",
//         "Bachelor of Engineering (BEng)",
//         "Master of Engineering (MEng)",
//         "Bachelor of Nursing (BN)",
//         "Doctor of Medicine (MD)",
//         "Juris Doctor (JD)",
//         "Bachelor of Social Work (BSW)",
//         "Master of Social Work (MSW)",
//         "Diploma",
//         "Certificate"
// ];

// export const fieldOfStudyData = [
//     "Computer Science (CSE)",
//         "Electrical and Electronics Engineering (EEE)",
//         "Mechanical Engineering",
//         "Civil Engineering",
//         "Information Technology",
//         "Software Engineering",
//         "Data Science",
//         "Artificial Intelligence",
//         "Business Administration",
//         "Accounting",
//         "Finance",
//         "Marketing",
//         "Human Resource Management",
//         "Economics",
//         "Psychology",
//         "Biology",
//         "Chemistry",
//         "Physics",
//         "Environmental Science",
//         "Nursing",
//         "Pharmacy",
//         "Graphic Design",
//         "Web Development",
//         "Information Systems",
//         "Statistics",
//         "Mathematics",
//         "Cybersecurity", 
//         "Network Administration", 
//         "Game Design", 
//         "Digital Media", 
//         "Interior Design", 
//         "Fashion Design", 
//         "Public Relations", 
//         "Hospitality Management", 
//         "Supply Chain Management", 
//         "Project Management", 
//         "International Business", 
//         "Real Estate", 
//         "Sports Management", 
//         "Film Studies", 
//         "Music Production", 
//         "Theater Arts", 
//         "Creative Writing", 
//         "Environmental Studies", 
//         "Public Health", 
//        "Health Information Management", 
//        "Nutrition", 
//        "Occupational Therapy", 
//        "Physical Therapy", 
//        "Aerospace Engineering", 
//        "Chemical Engineering", 
//        "Biomedical Engineering",
//        "Forensic Science", 
//        "Marine Biology", 
//        "Astrophysics",
//        "Political Science", 
//        "Sociology", 
//        "Anthropology", 
//        "Special Education", 
//        "Early Childhood Education", 
//        "Data Analytics", 
//        "Artificial Intelligence Ethics", 
//        "Blockchain Technology", 
//        "Digital Marketing", 
//        "Linguistics", 
//        "Foreign Languages",
//        "Entrepreneurship", 
//        "Business Analytics"
// ];


export const allSkills = {
    "docs": [
        {
            "id": "732e1796-7a71-4931-bd5a-239c1f015edb",
            "title": "test skills 2",
            "industryTypeId": [
                {
                    "id": "02c39e58-cb1c-49f7-97ab-1a93a29619f8",
                    "title": "test industry type",
                    "description": null,
                }
            ],
        },
    ],
}

export const degreeLevelData = {
    "docs": [
        {
            "id": "053cd830-ba1e-4b19-91e3-3fc9ee482d73",
            "title": "test degree level",
        }
    ],
}

export const fieldOfStudyData = {
    "docs": [
        {
            "id": "d4ea9836-73b4-40b1-9291-0d78ab42c0ef",
            "title": "test field",
        }
    ],
}

export const allJobRoles = {
    "docs": [
        {
            "id": "ddcc16e7-67d1-4094-998d-25497543ec0f",
            "title": "Test job role",
            "industryTypeId": [
                {
                    "id": "02c39e58-cb1c-49f7-97ab-1a93a29619f8",
                    "title": "test industry type",
                    "description": null,
                    "updatedAt": "2025-01-21T10:57:51.191Z",
                    "createdAt": "2025-01-21T10:57:51.191Z"
                },
                {
                    "id": "7143c546-dcfb-433e-aa24-7e5376446026",
                    "title": "test industry",
                    "description": "test description",
                    "updatedAt": "2025-01-21T11:40:28.880Z",
                    "createdAt": "2025-01-21T11:40:28.880Z"
                }
            ],
            "updatedAt": "2025-01-21T11:41:08.329Z",
            "createdAt": "2025-01-21T11:41:08.329Z"
        }
    ],
    "hasNextPage": false,
    "hasPrevPage": false,
    "limit": 10,
    "nextPage": null,
    "page": 1,
    "pagingCounter": 1,
    "prevPage": null,
    "totalDocs": 1,
    "totalPages": 1
}

export const allDesignation = {
    "docs": [
        {
            "id": "437543c8-1be8-41ad-bcf9-484346ba13ff",
            "title": "test designation",
            "industryTypeId": [
                {
                    "id": "7143c546-dcfb-433e-aa24-7e5376446026",
                    "title": "test industry",
                    "description": "test description",
                    "updatedAt": "2025-01-21T11:40:28.880Z",
                    "createdAt": "2025-01-21T11:40:28.880Z"
                }
            ],
            "updatedAt": "2025-01-23T09:52:24.647Z",
            "createdAt": "2025-01-23T09:52:17.261Z"
        }
    ],
    "hasNextPage": false,
    "hasPrevPage": false,
    "limit": 10,
    "nextPage": null,
    "page": 1,
    "pagingCounter": 1,
    "prevPage": null,
    "totalDocs": 1,
    "totalPages": 1
}

export const allJobTypes = {
    "docs": [
        {
            "id": "86505c23-f08b-4cdf-8b76-3cab17ad6750",
            "title": "test job type",
            "updatedAt": "2025-01-23T09:53:33.106Z",
            "createdAt": "2025-01-23T09:53:33.106Z"
        }
    ],
    "hasNextPage": false,
    "hasPrevPage": false,
    "limit": 10,
    "nextPage": null,
    "page": 1,
    "pagingCounter": 1,
    "prevPage": null,
    "totalDocs": 1,
    "totalPages": 1
}

export const allEmploymentTypes = {
    "docs": [
        {
            "id": "e39afd34-dad9-4f0d-a6a0-4e29332f6944",
            "title": "test employee type",
            "updatedAt": "2025-01-23T09:53:50.176Z",
            "createdAt": "2025-01-23T09:53:50.176Z"
        }
    ],
    "hasNextPage": false,
    "hasPrevPage": false,
    "limit": 10,
    "nextPage": null,
    "page": 1,
    "pagingCounter": 1,
    "prevPage": null,
    "totalDocs": 1,
    "totalPages": 1
}