export const data = [
    {
      id: "m5gr84i9",
      jobTitle: "Full-Stack Engineer",
      applicantName: "Shoishob Al-Baki",
      applicantEmail: "shoishob@hotmail.com",
      status: "Shortlisted",
      CVScore: 50,
      deadline: new Date("2024-11-01"),
    },
    {
      id: "3u1reuv4",
      jobTitle: "Software Engineer",
      applicantName: "Ataullah",
      applicantEmail: "ataullah@gmail.com",
      status: "Hired",
      CVScore: 65,
      deadline: new Date("2024-11-05"),
      interviewSchedule: new Date("2024-11-14"),
    },
    {
      id: "derv1ws0",
      jobTitle: "Human Resources Manager",
      applicantName: "Shoikot Arfin",
      applicantEmail: "arfin@outlook.com",
      status: "Shortlisted",
      CVScore: 50,
      deadline: new Date("2024-11-01"),
      interviewSchedule: new Date("2024-11-10"),
    },
    {
      id: "5kma53ae",
      jobTitle: "Marketing Manager",
      applicantName: "Shoishob Al-Baki",
      applicantEmail: "shoishob@hotmain.com",
      status: "Applied",
      CVScore: 50,
      deadline: new Date("2024-11-01"),
    },
    {
      id: "bhqecj4p",
      jobTitle: "QA Engineer",
      applicantName: "Ashfaq Tanzim",
      applicantEmail: "ashfaq@gmail.com",
      status: "Hired",
      CVScore: 60,
      deadline: new Date("2024-10-01"),
      interviewSchedule: new Date("2024-10-10"),
    },
  ];
  